name: local_notifications
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  path: any

  cupertino_icons: ^0.1.2
  flutter_local_notifications: ^1.3.0
  android_alarm_manager: ^0.4.5+10
  shared_preferences: ^0.5.6
  e2e: 0.3.0
  path_provider: ^1.3.1
  schedule_controller: ^0.1.3+1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


